apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: suno-export-k8s-operator
rules:
  - apiGroups: [""]
    resources: ["configmaps", "services", "serviceaccounts", "pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["suno.mikegales.dev"]
    resources: ["sunoexportclusters"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["suno.mikegales.dev"]
    resources: ["sunoexportclusters/status"]
    verbs: ["get", "update", "patch"]
