apiVersion: v1
kind: Secret
metadata:
  name: suno-export-runtime
  namespace: suno-export
type: Opaque
stringData:
  postgres-url: postgres://suno_exporter:maurice4gilbert9SEARCHED-wade@cnpg-pgsql.galesnet.com:5432/suno_export
  mqtt-url: mqtt://mqtt.galesnet.com:1883
