import type { RawApiResponse, ISunoTrackResponse } from "./ISunoTrackResponse";

export interface ISongData {
  title?: string | null;
  clipId: string;
  style?: string | null;
  thumbnail?: string | null;
  model?: string | null;
  duration?: string | null;
  songUrl: string;
  liked: boolean;
  artistName?: string | null;
  lyrics?: string;
  creationDate?: Date | null;
  weirdness?: number | null;
  styleStrength?: number | null;
  audioStrength?: number | null;
  remixParent?: string;
  tags?: string[];
  comment?: string;
  upload?: boolean;
  negativeTags?: string[];
  isHidden?: boolean;
  gptDescriptionPrompt?: string | null;
  mashupSource?: string[];
  personaId?: string | null;
  personaName?: string | null;
  projectName?: string | null;
  explicit?: boolean;
  flaggedReason?: string | null;
  mp3Status?: string;
  wavStatus?: string;
  alacStatus?: string;
  flacStatus?: string;
  imageStatus?: string;
  mp3Timestamp?: Date | null;
  wavTimestamp?: Date | null;
  alacTimestamp?: Date | null;
  flacTimestamp?: Date | null;
  rawApiResponse?: RawApiResponse | ISunoTrackResponse;
}
