apiVersion: v1
kind: ConfigMap
metadata:
  name: suno-export-filebeat
  namespace: suno-export
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: filestream
        id: suno-export-containers
        enabled: true
        prospector.scanner.symlinks: true
        paths:
          - /var/log/containers/*suno-export*.log
        parsers:
          - container: ~
        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
                - logs_path:
                    logs_path: "/var/log/containers/"
          - decode_json_fields:
              fields: ["message"]
              target: ""
              overwrite_keys: true
              add_error_key: true
          - add_fields:
              target: ""
              fields:
                stack: suno-export
                environment: ${SUNO_EXPORT_ENVIRONMENT}
    processors:
      - add_host_metadata: ~
      - add_cloud_metadata: ~
    output.elasticsearch:
      hosts: ["${ELASTICSEARCH_HOSTS}"]
      username: "${ELASTICSEARCH_USERNAME}"
      password: "${ELASTICSEARCH_PASSWORD}"
      index: "suno-export-logs"
    setup.template.name: "suno-export-logs"
    setup.template.pattern: "suno-export-logs-*"
