apiVersion: v1
kind: Secret
metadata:
  name: suno-export-filebeat
  namespace: suno-export
type: Opaque
stringData:
  elasticsearch-hosts: https://your-es:9200
  elasticsearch-username: filebeat_suno_export
  elasticsearch-password: change-me
  environment: local
